spring:
  config:
    activate:
      on-profile: "default"
  application: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
#  security:
#    enabled: false
  endpoint:
#    healt:
#      show-details:always
  endpoints:
    web:
      exposure:
        include:
          - "*"

---

